image:
- Visual Studio 2017
build: off

init:
  - git config --global core.autocrlf input

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - md target\classes

test_script:
    - javac -cp lib\swoval/file-tree-views-2.1.1.jar src\main\java\build\performance\Main.java -d target/classes
    - java -cp "target\classes;src\main\resources;lib\swoval\file-tree-views-2.1.1.jar" build.performance.Main -i 10 -w 5 -e 5000 sbt-1.3.0 sbt-0.13.7 gradle-5.4.1 mill-0.3.6 -j "C:\Program Files\Java\jdk1.8.0"

cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
