image:
- Visual Studio 2017
build: off

init:
  - git config --global core.autocrlf input

install:
  - SET JAVA_HOME: C:\Program Files\Java\jdk11
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - SET CI=true

  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/sbt/sbt/releases/download/v1.0.4/sbt-1.0.4.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - SET PATH=C:\sbt\sbt\bin;%PATH%
  - SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g -Dsbt.supershell=never -Dfile.encoding=UTF8
test_script:
    - sbt "run -i 20 -w 3 -j C:\Program Files\Java\jdk1.8.0 sbt-1.3.0 sbt-0.13.17 gradle-5.4.1"

cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
