image:
- Visual Studio 2017
build: off

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\watch-perf

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/sbt/sbt/releases/download/v1.1.5/sbt-1.1.5.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - SET SBT_VER=1.3.0-RC1
  - SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g -Dfile.encoding=UTF8 -Dsbt.version=1.3.0-RC1
  - git clone -b 1.3.0-RC1-fixes https://github.com/eatkins/sbt
  - cd sbt
  - SET OLD_PATH=%PATH%
  - SET PATH="C:\Program Files\Java\jdk1.8.0\bin";%OLD_PATH%
  - java -jar C:\sbt\sbt\bin\sbt-launch.jar publishLocal

test_script:
    - cd c:\projects\watch-perf
    - SET PATH=%JAVA_HOME%\bin;%OLD_PATH%
    - md target\classes
    - javac -cp lib\swoval\file-tree-views-2.1.1.jar src\main\java\build\performance\Main.java -d target\classes
    - java -cp "target\classes;src\main\resources;lib\swoval\file-tree-views-2.1.1.jar" build.performance.Main -i 10 -w 5 -e 5000 sbt-0.13.17 sbt-1.3.0 mill-0.3.6 gradle-5.4.1 -j "C:\Program Files\Java\jdk1.8.0"

cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\AppData\Local\Coursier\cache\v1'
  - '%USERPROFILE%\.sbt'
