language: java

env:
  global:
  - TRAVIS_JDK=adopt@1.11.0-3

matrix:
  include:
   - os: linux
     language: java
     dist: trusty
     env:
         WATCH_JAVA_HOME=~/.jabba/jdk/adopt@1.11.0-3

   - os: osx
     language: java
     osx_image: xcode9.3
     env:
         WATCH_JAVA_HOME=~/.jabba/jdk/adopt@1.11.0-3/Contents/Home

before_install:
    - rm -r $(find $HOME/.sbt -name "*-SNAPSHOT") || true
    - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash; . ~/.jabba/jabba.sh
    - git clone --single-branch --branch terminal-fixes-appveyor https://github.com/eatkins/sbt.git /tmp/sbt-build
    - ~/.jabba/bin/jabba install adopt@1.11.0-3
    - wget https://github.com/sbt/sbt/releases/download/v1.3.13/sbt-1.3.13.tgz
    - tar -xvf sbt-1.3.13.tgz
    - rm sbt-1.3.13.tgz
    - mv sbt /tmp/sbt
    - DIR=$(pwd)
    - cd /tmp/sbt-build
    - /tmp/sbt/bin/sbt publishLocalBin
    - cd $DIR
script:
    - $WATCH_JAVA_HOME/bin/javac -cp lib/swoval/file-tree-views-2.1.1.jar src/main/java/build/performance/Main.java -d target/classes
    - $WATCH_JAVA_HOME/bin/java -cp "target/classes:src/main/resources:lib/swoval/file-tree-views-2.1.1.jar" build.performance.Main -i 11 -w 5 -e 5000 sbt-1.4.0-SNAPSHOT

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache/v1
    - $HOME/Library/Caches/Coursier/v1
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
  - rm -r $(find $HOME/.sbt -name "*-SNAPSHOT") || true
