language: java

env:
  global:
  - TRAVIS_JDK=adopt@1.11.0-3

matrix:
  include:
   - os: linux
     language: java
     dist: trusty

   - os: osx
     language: java
     osx_image: xcode9.3

before_install:
    - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh
    - ~/.jabba/bin/jabba install adopt@1.11.0-3
install:

script:
    - $JABBA_HOME/bin/javac -cp lib/swoval/file-tree-views-2.1.1.jar src/main/java/build/performance/Main.java -d target/classes
    - $JABBA_HOME/bin/java -cp "target/classes:src/main/resources:lib/swoval/file-tree-views-2.1.1.jar" build.performance.Main -i 10 -w 5 -e 5000 sbt-1.3.0 sbt-0.13.17 gradle-5.4.1 mill-0.3.6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
